name: Brandon Vlaar ðŸŒŽ
description: Thoughts about tech and environment.
meta_description: "Thoughts about tech and environment"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: 'https://www.brandonvlaar.com/'
domain_name: 'https://www.brandonvlaar.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            "Vlaar's Thoughts"
author:         'Brandon Vlaar'
